import{a as p,S as h,i as l}from"./assets/vendor-6e0bf343.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const s of e)if(s.type==="childList")for(const d of s.addedNodes)d.tagName==="LINK"&&d.rel==="modulepreload"&&i(d)}).observe(document,{childList:!0,subtree:!0});function a(e){const s={};return e.integrity&&(s.integrity=e.integrity),e.referrerPolicy&&(s.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?s.credentials="include":e.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function i(e){if(e.ep)return;e.ep=!0;const s=a(e);fetch(e.href,s)}})();async function g(o,r){p.defaults.baseURL="https://pixabay.com/api/";const i=`?key=43825908-e00f2a501e8ab3b01ba78a8cd&q=${o}&image_type=photo&orientation=horizontal&safesearch=true&page=${r}&per_page=15`;try{const{data:e}=await p.get(i);return e}catch(e){console.log(e)}}function u(o,r){const a=o.reduce((i,e)=>i+=`<div class="gallery-item">
            <a href="${e.largeImageURL}"><img src="${e.webformatURL}" alt="${e.tags}"  width="360"/></a>
            <div class="info">
                <p>Likes <span></span>${e.likes}</span></p>
                <p>Views <span></span>${e.views}</span></p>
                <p>Comments <span></span>${e.comments}</span></p>
                <p>Downloads <span></span>${e.downloads}</span></p>
            </div>
                </div>`,"");r.insertAdjacentHTML("beforeend",a)}const t={formEL:document.querySelector("#form"),inputEL:document.querySelector("#image-input"),galleryEL:document.querySelector("#gallery"),loadMoreBtn:document.querySelector(".load-more"),loaderEl:document.querySelector("#loader-js")};let m=new h("#gallery a",{captionsData:"alt",captionDelay:250}),c="",n=1;function f(o){if(o.preventDefault(),t.loadMoreBtn.classList.remove("is-visible"),n=1,t.galleryEL.innerHTML='<span class="loader"></span>',c=t.inputEL.value.trim(),c==="")return t.galleryEL.innerHTML="",l.show({title:'<div class="error-remark"><img src="./img/error.svg" alt="error" class="error-svg"><span class="error-text">Introduction field please enter the value to search</span></div>',titleSize:"20px",message:"",backgroundColor:"red",position:"topRight"});g(c,n).then(r=>{if(t.galleryEL.innerHTML="",r.totalHits===0)return l.show({title:'<div class="error-remark"><img src="./img/error.svg" alt="error" class="error-svg"><span class="error-text">Sorry, there are no images matching your search query. Please try again!</span></div>',titleSize:"20px",message:"",backgroundColor:"red",position:"topRight"});u(r.hits,t.galleryEL),m.refresh(),r.totalHits>15&&t.loadMoreBtn.classList.add("is-visible")}).catch(r=>{t.galleryEL.innerHTML="",l.show({title:'<div class="error-remark"><img src="./img/error.svg" alt="error" class="error-svg"><span class="error-text">An error occurred while fetching the images. Please try again later.</span></div>',titleSize:"20px",message:"",backgroundColor:"red",position:"topRight"}),console.error("Error fetching images:",r)}),t.formEL.reset()}function y(o){t.loaderEl.innerHTML='<span class="loader"></span>',n+=1,g(c,n).then(r=>{if(t.loaderEl.innerHTML="",u(r.hits,t.galleryEL),m.refresh(),t.galleryEL){const a=t.galleryEL.getBoundingClientRect().height;window.scrollBy({top:a*2,behavior:"smooth"})}Math.ceil(r.totalHits/15)===n&&(t.loadMoreBtn.classList.remove("is-visible"),l.show({title:'<div class="error-remark"><img src="./img/error.svg" alt="error" class="error-svg"><span class="error-text">We are sorry, but you have reached the end of search results.</span></div>',titleSize:"20px",message:"",backgroundColor:"red",position:"topRight"}))}).catch(r=>{t.loaderEl.innerHTML="",l.show({title:'<div class="error-remark"><img src="./img/error.svg" alt="error" class="error-svg"><span class="error-text">An error occurred while loading more images. Please try again later.</span></div>',titleSize:"20px",message:"",backgroundColor:"red",position:"topRight"}),console.error("Error loading more images:",r)})}t.formEL.addEventListener("submit",f);t.loadMoreBtn.addEventListener("click",y);
//# sourceMappingURL=commonHelpers.js.map
